name: sp500-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.22.0
  - pandas>=1.5.0
  - matplotlib>=3.6.0
  - scikit-learn>=1.2.0
  - lxml
  - networkx>=3.0.0
  - pytorch
  - torchvision
  - pip
  - pip:
    - torch-geometric>=2.3.0
    - yfinance>=0.2.28